### PR TITLE
Update update2deb.yml

### PR DESCRIPTION
**Pull request by ryanfortner**

### CODE REVIEW

**Comment by ryanfortner** [comment]
This will trigger the deb to be built upon release creation. The deb will be versioned according to the latest github release.

Not tested, but should work. After merging, try creating a release. The deb should be created and uploaded to that release.

**Comment by Crilum** [comment]
@ryanfortner echo seemed to work for me.

**Comment by ryanfortner** [comment]
@Crilum could you try creating a release please?

**Comment by Crilum** [comment]
Well, no matter what I do:
```
dpkg-deb: error: failed to open package info file 'updatedeb/DEBIAN/control' for reading: No such file or directory
update
Error: Process completed with exit code 2.
```

**Pull request merged**
