### PR TITLE
Add deb file

### PR DESCRIPTION
**Pull request by ryanfortner**
I've created a deb file for the program. If you'd like, I can also open a PR to update the `install` script.

### CODE REVIEW

**Comment by Crilum** [comment]
Thanks @ryanfortner! The deb works.
I think we would need a GitHub Actions workflow to create a deb, because I frequently make changes to update. It would be too hard to create a deb every time I make a change (or merge a PR). It doesn't need to be automatic though, I would just trigger it when I got all the bugs out of the latest version. 

Also, thanks for fixing the typo in the README!

**Comment by ryanfortner** [comment]
I created the deb using my [script](https://github.com/ryanfortner/deb-builder), if you want you can take a look at it to see how it was created. 

I can work on a GitHub workflow later

**Comment by Crilum** [comment]
We also need a better versioning system then just the date. What about something like this:

0.13.26 (just an example)

- First digit: Super big changes, or when the second two digits get to 100
- Second two digits: large changes, like adding a big feature like a customisation feature for the `all` arg
- Last two digits: small changes like bug fixes

**Comment by ryanfortner** [comment]
I think this pr can be merged. I can open another one for scripts/github workflow

**Comment by Crilum** [comment]
@ryanfortner I've made a workflow that makes a deb, and uploads it to the action. I'll update the README to say that stable debs can be found in the `debs` folder, and development debs can be found in the actions runs.

**Comment by Crilum** [comment]
I'm not sure how to make the workflow version the debs, so if you know how, I could use a little help with that :smile:.

**Pull request merged**
