### PR TITLE
Update update2deb.yml

### PR DESCRIPTION
**Pull request by ryanfortner**
moved `dpkg-deb` command to the prepare for building task

@Crilum

### CODE REVIEW

**Comment by Crilum** [comment]
```
dpkg-deb: error: parsing file 'updatedeb/DEBIAN/control' near line 11 package 'update':
 end of file before value of field 'Version' (missing final newline)
Error: Process completed with exit code 2.
```

**Comment by Crilum** [comment]
I tested the LATEST code and github says this:
```
$ curl -s https://api.github.com/repos/Crilum/update/releases/latest
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-the-latest-release"
}
```

**Comment by ryanfortner** [comment]
> I tested the LATEST code and github says this:
> 
> ```
> $ curl -s https://api.github.com/repos/Crilum/update/releases/latest
> {
>   "message": "Not Found",
>   "documentation_url": "https://docs.github.com/rest/reference/repos#get-the-latest-release"
> }
> ```

@Crilum that's because there are no public releases.

**Comment by Crilum** [comment]
Yeah sorry, I just realized that..

**Comment by Crilum** [comment]
I now get this again:
```
dpkg-deb --build updatedeb/ update_${LATEST}_all.deb
  echo "DEB=$(basename update*.deb)" >> $GITHUB_ENV 
  shell: /usr/bin/bash -e {0}
  env:
    DIR: /home/runner/work/update/update
dpkg-deb: error: failed to open package info file 'updatedeb//DEBIAN/control' for reading: No such file or directory
Error: Process completed with exit code 2.
```

**Comment by Crilum** [comment]
Wait, is the path supposed to have two slashes?

**Comment by Crilum** [comment]
Any idea?
```
/usr/bin/docker run --name gactsuploadtoreleaselatest_0d1b73 --label e28490 --workdir /github/workspace --rm -e DIR -e DEB -e GITHUB_TOKEN -e INPUT_FILE -e INPUT_TYPE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/update/update":"/github/workspace" gacts/upload-to-release:latest
curl: (22) The requested URL returned error: 404 
```

**Comment by ryanfortner** [comment]
@Crilum try making a _new_ release.

**Comment by Crilum** [comment]
I feel like GitHub is having some problems, because there aren't two slashes in the YAML...
```
dpkg-deb --build updatedeb/ update_${LATEST}_all.deb
  echo "DEB=$(basename update*.deb)" >> $GITHUB_ENV 
  shell: /usr/bin/bash -e {0}
  env:
    DIR: /home/runner/work/update/update
dpkg-deb: error: failed to open package info file 'updatedeb//DEBIAN/control' for reading: No such file or directory
Error: Process completed with exit code 2.
```

**Comment by ryanfortner** [comment]
@Crilum have you tried adding a `ls` in the yaml just to make sure the control file is actually there?

**Comment by Crilum** [comment]
yeah, the current one works though. It just looks like GitHub is reading the old version that had a slash at the end of the path in dpkg.

**Comment by Crilum** [comment]
The old file github is using

**Comment by Crilum** [comment]
Ok, I got it working. It was doing that because I was releasing an older tag.. :man_facepalming: Thanks for your help!

**Comment by ryanfortner** [comment]
> Ok, I got it working. It was doing that because I was releasing an older tag.. 🤦‍♂️ Thanks for your help!

Great! I'm glad I could help.

**Comment by Crilum** [comment]
I tagged you in the release, just so you know!

**Comment by ryanfortner** [comment]
@Crilum one more suggestion, the releases tab isn't visible on the repository details, could you enable it please?

**Comment by Crilum** [comment]
Oh yeah, I forgot about that! One sec.

**Comment by Crilum** [comment]
Done.

**Pull request merged**
